name: recruitment_excercise_aramis
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - pytorch-cpu
  - torchvision
  - tensorflow
  - nibabel
  - matplotlib  
  - pytest 
  
  
